### ISSUE TITLE
configure: make libflac really optional

### ISSUE THREAD

**Issue by eblanca** [xiph/opus-tools#52]
opus-tools can actually be built without flac support, but the default behavior for configure is to raise an error when flac is not detected, why? This should be optional, as in vorbis-tools.
Well, when the user asks for flac AND the detection fails, then an error is due but why halt the build when flac is optional?

**Comment by mark4o** [comment]
By default opus-tools is built with FLAC support, but this can be disabled by configuring with "./configure --without-flac".  If the --without-flac option is used, it will not look for FLAC.

Some packages check for optional dependencies and turn them off automatically if not found, but this can lead unintentionally missing features.  This way, if you don't want the feature you can intentionally turn it off, but it won't be missing by accident, because you built the libraries in the wrong order or had them in the wrong directory or some other reason.

**Comment by eblanca** [comment]
ok
